### ISSUE TITLE
Rastreamento da Arquitetura

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#100]
## Descrição da Issue
Documentar o rastreamento e as decisões de arquitetura, tomadas durante o desenvolver do projeto, para serem apresentadas na R1.

### Tasks:
- [x] Fazer o rastreamento das referências de decisões arquiteturais;
- [x] Documentar todas as questões pendentes;

### Critérios de aceitação
- [ ] Referências rastreadas e documentadas
