### ISSUE TITLE
Criação de componente: Drawer

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#101]
## Descrição da Issue
Deve-se criar um drawer animado como componente reutilizável, para que se possa ser utilizada no front-end de maneira simples e direta.

### Tasks:
- [x] Criar o componente de drawer
- [x] Tornar fácilmente reutilizável

### Critérios de aceitação
- [x] Em typescript, reactJS
- [x] De acordo com o protótipo
