### ISSUE TITLE
Refatoração do CSS de acordo com a Arquitetura

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#103]
## Descrição da Issue
Refatorar os arquivos de CSS de acordo com a arquitetura definida para o projeto.

### Tasks:
- [x] Refatorar CSS do projeto

### Critérios de aceitação
- [x] Arquivos de acordo com a nova arquitetura
- [x] CSS de acordo com a identidade visual
