### ISSUE TITLE
Preparar Slide da R1

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#112]
## Descrição da Issue
Criar os slides a serem usados na gravação do vídeo para a R1. Devem ser abordados os principais tópicos requisitados para a apresentação, de acordo com a ementa da disciplina

### Tasks:
- [ ] Criar slides
- [ ] Adicionar gráficos, resumos de documentos

### Critérios de aceitação
- [ ] De acordo com a identidade visual
- [ ] De acordo com o roteiro
