### ISSUE TITLE
Configurar o Flagr

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#128]
## Descrição da Issue
Integrar o flaggr ao frontend para o desenvolvimento de feature toggles

### Tasks:
- [x] Adicionar a imagem do flaggr ao docker-compose do front
- [x] Refatorar código para aceitar feature flags
- [x] Estudar um pouco mais sobre feature toggles

### Critérios de aceitação
- [x] Ter o front funcionando com feature toggles
