### ISSUE TITLE
Implementar Certificados HTTPS

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#129]
## Descrição da Issue
Implementar na aplicação a segurança do certificado HTTPS, para garantir aos usuários uma navegação segura

### Tasks:
- [ ] Adicionar ao projeto certificados HTTPS
- [ ] Criar os hooks necessários para que a navegaçao da aplicação possa ser segura para o usuário

### Critérios de aceitação
- [ ] Certificado HTTPS implementado no deploy
