### ISSUE TITLE
Pesquisar cronjob e implementar coleta de métricas

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#131]
## Descrição da Issue
Pesquisar sobre implementação de cronjob em kubernetes, para que depois possa ser utilizado no projeto no trigger de e-mails, e implementar a coleta de métricas de código dentro do deploy da aplicação

### Tasks:
- [ ] Pesquisar sobre implementação de cronjob em kubernetes
- [ ] Implementar coleta de métricas da aplicação em CI/CD

### Critérios de aceitação
- [ ] Pesquisa documentada
- [ ] CI/CD realizando a coleta de métricas
