### ISSUE TITLE
Mapear contatos das ouvidorias de órgãos públicos

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#132]
## Descrição da Issue
Mapear e-mails de contatos para ouvidorias dos órgãos públicos e suas categorias, para que se possa ter uma noção de com quem iremos entrar em contato

### Tasks:
- [x] Mapear contatos das ouvidorias
- [x] Incluir categorias
- [x] Escrever um documento com tais

### Critérios de aceitação
- [x] Documentos de ouvidorias e categorias mapeadas

**Comment by MatheusBlanco** [comment]
https://docs.google.com/spreadsheets/d/1n7ftO6I2-LaG5niQ65_SoZ6FN-UqIcWOODlCpp6UCSE/edit#gid=0
