### ISSUE TITLE
Configurar ESLINT nos repositórios de microsserviços

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#142]
## Descrição da Issue
Deve-se configurar o ESLint para que os repositórios do back-end possam seguir os padrões de código de typescript

### Tasks:
- [x] Configurar no Complaint
- [x] Configurar no Users
- [x] Configurar no Mailer
- [x] Configurar no Gateway
- [x] Configurar no Reports

### Critérios de aceitação
- [x] ESLint configurado no complaint
- [x] ESLint configurado no reports
- [x] ESLint configurado no mailer
- [x] ESLint configurado no users
- [x] ESLint configurado no gateway

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.
