### ISSUE TITLE
Popular e configurar o repositório de users

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#143]
## Descrição da Issue
Deve-se refatorar o código do repositório de user de acordo com as decisões discutidas na sprint planning

### Tasks:
- [ ] Configurar morgan para logs de requests
- [ ] Popular o repo de users com informações mockadas
- [ ] Fazer pathmapping
- [ ] Montar handler das exceções
- [ ] Typescript com ponto e vírgula
- [ ] Remover query de logs do typeorm

### Critérios de aceitação
- [ ] Pathmapped
- [ ] Usuários mockados seedados no serviço de users
- [ ] Exceções com listeners
- [ ] Morgan configurado
