### ISSUE TITLE
Refatorar código do front-end

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#145]
## Descrição da Issue
Deve-se refatorar o código do front-end de acordo com as decisões discutidas na sprint planning

### Tasks:
- [x] Arrumar a navbar para que o botão de return apareça nas telas, menos na tela de denúncia
- [ ] Realizar o teste no botão

### Critérios de aceitação
- [x] Botão de retorno em todas as telas que não sejam o feed de denúncia
