### ISSUE TITLE
Refatorar código do serviço de complaint

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#146]
## Descrição da Issue
Deve-se refatorar o código do repositório de complaint de acordo com as decisões discutidas na sprint planning

### Tasks:
- [ ] Padronizar código em todo o repositório
- [ ] Criar camada de services 
- [ ] Fazer testes dos servides
- [ ] Fazer teste dos repositories
- [ ] Montar handler das exceções

### Critérios de aceitação
- [ ] Código padronizado
- [ ] Camada de services criada
- [ ] Serviços testados
- [ ] Exceções com listeners
