### ISSUE TITLE
Refatorar código do serviço de gateway

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#147]
## Descrição da Issue
Deve-se refatorar o código do repositório de gateway de acordo com as decisões discutidas na sprint planning

### Tasks:
- [x] Padronizar código em todo o repositório
- [x] Fazer testes dos serviços (supertest)
- [x] Configurar o Pathmapping
- [x] Configurar o Morgan
- [x] Montar handler das exceções
- [x] Typescript com ponto e vírgula

### Critérios de aceitação
- [x] Código padronizado
- [x] Serviços testados
- [x] Pathmapped
- [x] Logs das Requisições
- [x] Montar handler das exceções

**Comment by Victor-Buendia** [comment]
Para o ESLint fazer o ponto e vírgula aparecer o erro no VSCode, é necessário instalar a extensão do ESLint:

> Name: ESLint
Id: dbaeumer.vscode-eslint
Description: Integrates ESLint JavaScript into VS Code.
Version: 2.1.19
Publisher: Dirk Baeumer
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Colocamos nos scripts do `package.json` um yarn eslint também para funcionar. Ele faz a correção de onde falta ponto e vígula em todo o diretório /src.

`"eslint": "npx eslint src/ --fix"`
