### ISSUE TITLE
Refatoração do serviço de reports

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#148]
## Descrição da Issue
Deve-se refatorar o código do repositório de reports de acordo com as decisões discutidas na sprint planning

### Tasks:
- [x] Padronizar código em todo o repositório
- [x] Configurar morgan para logs de requests
- [x] Fazer pathmapping
- [x] Fazer testes dos serviços
- [x] Montar handler das exceções
- [x] Typescript com ponto e vírgula

### Critérios de aceitação
- [x] Código padronizado
- [x] Pathmapped
- [x] Serviços testados
- [x] Exceções com listeners
- [x] Morgan configurado

**Comment by Arthur-Matos** [comment]
Pathmapping ja feito pelo @Phe0

**Comment by Arthur-Matos** [comment]
Essa issue esta sendo realizada juntamente ao PR 3 do repositório de reports
