### ISSUE TITLE
Refatoração do serviço de mailer

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#149]
## Descrição da Issue
Deve-se refatorar o código do repositório de mailer de acordo com as decisões discutidas na sprint planning

### Tasks:
- [x] Padronizar código em todo o repositório
- [x] Configurar morgan para logs de requests
- [ ] Fazer pathmapping
- [x] Fazer testes dos serviços
- [x] Montar handler das exceções
- [ ] Typescript com ponto e vírgula

### Critérios de aceitação
- [x] Código padronizado
- [ ] Pathmapped
- [x] Serviços testados
- [x] Exceções com listeners
- [x] Morgan configurado
