### ISSUE TITLE
Configuração do Sentry nos repositórios

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#156]
## Descrição da Issue
Configurar o serviço de sentry em todos os repostórios do projeto a fim de ajudar o time a diagnosticar, arrumar e otimizar o código

### Tasks:
- [ ] Configurar o Sentry no repositório de reports
- [ ] Configurar o Sentry no repositório de mailer
- [ ] Configurar o Sentry no repositório de complaints
- [ ] Configurar o Sentry no repositório de users
- [ ] Configurar o Sentry no repositório de gateway
- [ ] Configurar o Sentry no repositório de front-end

### Critérios de aceitação
- [ ] Sentry configurado no mailer
- [ ] Sentry configurado no reports
- [ ] Sentry configurado no complaints
- [ ] Sentry configurado no gateway
- [ ] Sentry configurado no users
- [ ] Sentry configurado no front-end
