### ISSUE TITLE
HOTFIX - Cors e Security HotSpots

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#162]
## Descrição da Issue
O SonarCloud está apontando falhas de segurança em requisições. Devem-se identificar e arrumar essas falhar para proteger a integridade de dados

### Tasks:
- [ ] Checar e corrigir as configurações do cors
- [ ] Checar e corrigir configurações de segurança de hotspots

### Critérios de aceitação
- [ ] Falhas de segurança e logs de erro corrigidos no sonar
- [ ] Integridade de dados garantida

**Comment by MatheusBlanco** [comment]
Foi acertado que essa issue não será mais necessária. Será fechada
