### ISSUE TITLE
Roteiro de testes de usabilidade e percepções de usuário

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#171]
## Descrição da Issue
Deve-se rodar o projeto com um público real, e para que se possa sempre melhorar e revisar o projeto para que o mesmo possa alcançar seus objetivos, deve-se coletar as percepções de usuário.

### Tasks:
- [ ] Criar roteiro de usabilidade que compreenda UX, UI, objetivos de negócio
- [ ] Criar maneira de coletar e calcular as métricas para que se possa se utilizar dos resultados e melhorar do projeto

### Critérios de aceitação
- [ ] Roteiro criado e pronto para ser utilizado com grupo focal

**Comment by MatheusBlanco** [comment]
Issue realizada nos seguintes documentos: 
https://docs.google.com/document/d/1K5DFsy7HeVG7qKaRaHGXGcbtqCI947mZ9r5NEq_dB9Q/edit?usp=drivesdk

https://docs.google.com/spreadsheets/d/1VjCRBiOyqPTHOzv_BBj08WT0tYlJUXM4YF2d0NxCmBg/edit?usp=drivesdk
