### ISSUE TITLE
Mapear possíveis feature toggles

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#172]
## Descrição da Issue
Deve-se mapear, a partir das páginas e possíveis implementações existentes no front-end, quais funcionalidades poderiam ser afetadas por feature toggles, de maneira a criar releases diferenciadas de funcionalidades de acordo com casos específicos.

### Tasks:
- [ ] Planejar possíveis casos de feature toggles
- [ ] Criar plano de feature toggles por feature e quais casos a feature seria liberada ou restrita

### Critérios de aceitação
- [ ] Plano de feature toggles de fácil entendimento para ser implementado em sprints posteriores

**Comment by devsalula** [comment]
Issue realizada e documentada no seguinte, documento: https://docs.google.com/document/d/1JxKyOBXJzw4Ox1oHEebi-8A1IX7XVZHTUTrYCA0SWsg/edit?usp=sharing
