### ISSUE TITLE
Cobertura de Testes: Front-End

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#183]
## Descrição da Issue
Deve-se aumentar a porcentagem da cobertura de testes do serviço de front-end, para que se possa conformar com as exigências do sonarCloud e da matéria

### Tasks:
- [x] Testar a maior quantidade possível de funções;
- [x] Testar a maior quantidade possível de chamadas de API;
- [x] Testar a maior quantidade possível de telas;
- [x] Testar a maior quantidade possível de componentes;

### Critérios de aceitação
- [x] Cobertura de testes acima de 90%
