### ISSUE TITLE
Revisão: CI/CD

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#185]
## Descrição da Issue
Deve-se checar os processos de Continuous Integration e Continuous Deploy dos serviços pertinentes ao projeto Eccoar, garantindo que os mesmos estejam funcionando corretamente.

### Tasks:
- [ ] Checar e corrijir, se necessário, o CI/CD do serviço de complaint
- [ ] Checar e corrijir, se necessário, o CI/CD do serviço de gateway
- [ ] Checar e corrijir, se necessário, o CI/CD do serviço de mailer
- [ ] Checar e corrijir, se necessário, o CI/CD do serviço de reports
- [ ] Checar e corrijir, se necessário, o CI/CD do serviço de front-end

### Critérios de aceitação
- [ ] CI/CD de complaints funcionando corretamente
- [ ] CI/CD de gateway funcionando corretamente
- [ ] CI/CD de mailer funcionando corretamente
- [ ] CI/CD de reports funcionando corretamente
- [ ] CI/CD de front-end funcionando corretamente
