### ISSUE TITLE
Configurar CI/CD do repositório de Users

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#186]
## Descrição da Issue
O repositório de Users havia sido deprecado em favor de um novo repositório. Entretanto, o mesmo voltou a ser utilizado recentemente, com a adição de um banco de usuários e conexão com a Firebase Authentication. Deve-se realizar as tarefas de DevOps neste repositório para que a integração e deploy contínuo possam funcionar corretamente.

### Tasks:
- [ ] Configurar integração contínua com todas as etapas importantes (build, testes, eslint, sonar quality scan...)
- [ ] Configurar Deploy contínuo para que o serviço em homologação seja atualizado a cada nova tag de release gerada.

### Critérios de aceitação
- [ ] CI/CD configurados
