### ISSUE TITLE
Prototipar a tela da Landing Page

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#187]
## Descrição da Issue
Deve-se prototipar a tela da Landing page no front-end, para que o usuário possa ver informações de uso e legais sobre o sistema Eccoar

### Tasks:
- [x] Prototipar tela landing page
- [x] Seguir a identidade visual

### Critérios de aceitação
- [ ] Landing page prototipada e pronta para ser implementada

**Comment by MatheusBlanco** [comment]
A issue está sendo feita neste link: https://www.figma.com/file/y5ak8SDlqgaPKGfPIble7R/Projeto-Eccoar?node-id=123%3A859
