### ISSUE TITLE
HOTFIX - Flaggr e quantidade de votos

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#191]
## Descrição da Issue
Deve-se adequar o sistema para que o mesmo seja capaz de realizar as tarefas de geração de relatório e envio de e-mails com uma quantidade mutável de votos em cada denúncia, mas sem codar os valores diretamente no código da aplicação

### Tasks:
- [x] Criar um novo parâmetro de maxVotes na api de complaints
- [x] A rota de adicionar votos deve aceitar o novo parâmetro dentro do gateway
- [x] Deve-se criar uma feature flag para passar esse parâmetro a partir de flags determinadas, e o front deverá passar esse parâmetro para os outros serviços

### Critérios de aceitação
- [x] Feature flag com a quantidade de votos criada e comunicando com os serviços
- [x] Quantidade de votos mutável de maneira simples
