### ISSUE TITLE
Cobertura de testes

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#195]
## Descrição da Issue
Deve-se aumentar a porcentagem da cobertura de testes dos serviço do projeto, para que se possa conformar com as exigências do sonarCloud e da matéria

### Tasks:
- [ ] Testar a maior quantidade possível de funções;
- [ ] Testar a maior quantidade possível de chamadas de API;
- [ ] Testar a maior quantidade possível de telas;
- [ ] Testar a maior quantidade possível de componentes;

### Critérios de aceitação
- [ ] Cobertura de testes acima de 90%
