### ISSUE TITLE
Adicionar etapa na pipeline para salvar jsons do sonar

### ISSUE THREAD

**Issue by Phe0** [fga-eps-mds/2020.2-Eccoar#203]
## Descrição da Issue
Os jsons de métricas do sonar obtidos durante a pipeline, esta̍o sendo salvos apenas no gitlab. É necessário adicionar uma etapa na pipeline para que o artefato seja comitado no [repositório de métricas](https://github.com/Eccoar/2020.2-Eccoar-Analytics).

### Tasks:
- [ ] Organizar repósitório de analytics por pastas
- [ ] Adicionar etapa na pipeline
- [ ] Salvar o json obtido no repositório

### Critérios de aceitação
- [ ] O json do sonar deve ser salvo automaticamente no repositório de analytics ao se merjar um PR na main
- [ ] O repositório de analytics deve estar organizado por pastas representando cada um dos repositórios de código do projeto
- [ ] O nome dos arquivos json devem ter a data e horário em que foram gerados
