### ISSUE TITLE
Recuperar JSONs das Releases antigas

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#204]
## Descrição da Issue
Deve-se recuperar os JSONs das releases antigas para que se possa inseri-los nas releases previamente criadas e no repositório de analytics

### Tasks:
- [ ] Recuperar JSONs das releases antigas
- [ ] Inserir nas releases
- [ ] Inserir no repositório apropriado

### Critérios de aceitação
- [ ] JSONs recuperados
