### ISSUE TITLE
Análise de decisões de dados das Releases anteriores

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#205]
## Descrição da Issue
Deve-se documentar as decisões de projeto realizadas a partir das análises realizadas do sonar cloud

### Tasks:
- [ ] Documentar as decisões das releases passadas e recentes

### Critérios de aceitação
- [ ] Decisões documentadas das releases do serviço de complaint (Luiz Henrique)
- [ ] Decisões documentadas das releases do serviço de gateway (Luiz Pettengil)
- [ ] Decisões documentadas das releases do serviço de mailer (Sabanai)
- [ ] Decisões documentadas das releases do serviço de reports (Luiz Pettengil)
- [ ] Decisões documentadas das releases do serviço de users (Luiz Henrique)
- [ ] Decisões documentadas das releases do serviço de front-end (Sabanai)

**Comment by MatheusBlanco** [comment]
@LuizPettengill @luiz-herique @Sabanai104 , o repo com os JSONs https://github.com/Eccoar/2020.2-Eccoar-Analytics

**Comment by MatheusBlanco** [comment]
Repo do hilmer: https://github.com/fga-eps-mds/Analytics
