### ISSUE TITLE
Testes de usabilidade

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#222]
## Descrição da Issue
De maneira a se poder provar e coletar os feedbacks da proposta de valor do produto proposto, deve-se realizar testes de usabilidade e de valor com um grupo focal, seguindo-se roteiro específico

### Tasks:
- [ ] Cada membro deve realizar o teste com pelo menos um membro da família
- [ ] Os resultados devem ser anotados na [tabela](https://docs.google.com/spreadsheets/d/1VjCRBiOyqPTHOzv_BBj08WT0tYlJUXM4YF2d0NxCmBg/edit?usp=sharing)

### Critérios de aceitação
- [ ] Testes realizados
- [ ] Resultados anotados para que uma análise possa ser realizada a tempo da R2
