### ISSUE TITLE
Investigar duplicação de código no Sonar

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#223]
## Descrição da Issue
Todos os repositórios do projeto estão demonstrando que houve 0% de duplicação de código nas métricas coletadas. Acredita-se que pode ser um bug, deve-se investigar se é mesmo e se for, arrumar

### Tasks:
- [ ] Investigar a possibilidade da duplicação 0% ser um bug
- [ ] Corrigir a coleta de métrica caso esteja errada

### Critérios de aceitação
- [ ] Métrica analisada e corrigida
