### ISSUE TITLE
HOTFIX - Variáveis do FLAGR

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#226]
## Descrição da Issue
O front-end está mt dependente das flags do flagr para seu funcionamento. Caso uma das flags seja erroneamente apagada, como foi o caso do dia, o projeto irá quebrar por completo. Deve-se encontrar uma maneira de torná-lo independente.

### Tasks:
- [ ] Identificar as flags no front
- [ ] Tornar as variáveis das mesmas condicionais, para que não quebrem o front caso não existam

### Critérios de aceitação
- [ ] Front independente do flagr
