### ISSUE TITLE
Analytics: Estatística Descritiva

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#231]
## Descrição da Issue
Deve-se realizar a estatística descritiva das métricas coletadas do analytics e plotar os dados em tabelas (ex: média, moda, mediana, desvio padrão, variância, mínimo, máximo)

### Tasks:
- [ ] Realizar a estatística descritiva das métricas de cada release dos serviços
- [x] Plotar os valores em tabelas

### Critérios de aceitação
- [ ] Estatística descritiva das métricas realizada, por release
- [ ] Estatística descritiva das métricas realizada, por repositório

**Comment by Phe0** [comment]
A análise descritíva deve ser feita em cima das métricas m1, m2, m3, m7, m8 e m9.
Caso nem todas as métricas estejam disponíveis, apenas preparar o notebook para realizar a análise.
O Professor Hilmer mandou um slide no discord mostrando mais ou menso o que deve ser feito.
