### ISSUE TITLE
Analytics: THROUGHPUT, m7, m8, m9

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#232]
## Descrição da Issue
Deve-se utilizar do notebook confeccionado e dado pelo professor para que se possa calcular e analisar as medidas de THROUGHPUT m7, m8 e m9 das métricas dos repositórios

### Tasks:
- [ ] Rodar o script das medidas mencionadas, nas métricas
- [ ] Rodar por repositório

### Critérios de aceitação
- [ ] Medidas por métrica, coletadas
- [ ] As medidas foram calculadas e analisadas de acordo com as orientações do notebook dado pelo professor

**Comment by Phe0** [comment]
as métricas m7, m8 e m9 estão descritas em um dos notebooks do professors Hilmer.
Uma sugestão para realizar a coleta dessas métricas é baixas as issues do github como csv e importar como um pandas Dataframe.
