### ISSUE TITLE
Analytics: Medidas m1, m2 e m3

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#233]
## Descrição da Issue
Deve-se utilizar do notebook confeccionado e dado pelo professor para que se possa calcular e analisar as medidas de m1, m2 e m3 das métricas dos repositórios

### Tasks:
- [ ] Rodar o script das medidas mencionadas, nas métricas
- [ ] Rodar por repositório

### Critérios de aceitação
- [ ] Medidas por métrica, coletadas
- [ ] As medidas foram calculadas e analisadas de acordo com as orientações do notebook dado pelo professor

**Comment by Phe0** [comment]
Sugiro dar uma olhada nesse notebook [aqui](https://github.com/parlamentaqui/documentation/blob/master/analytics.ipynb) do grupo parlamentaaqui, que já fez uma certa análise em cima dessas métricas.
