### ISSUE TITLE
Analytics: Percentuais descritivos

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#234]
## Descrição da Issue
Deve-se apresentar uma tabela, contendo indicações numéricas dos percentis descritivos de cada uma das métricas coletadas de todas as releases dos repositórios, de maneira a se poder verificar a porcentagem de obtenção de cada uma

### Tasks:
- [ ] Criação da tabela
- [ ] Inserção dos valores das métricas por repo e por release, em formato de percentil descritivo

### Critérios de aceitação
- [ ] Tabela com os valores percentuais inseridos
- [ ] Tabela de fácil visualização e de fácil manuseio

**Comment by Phe0** [comment]
Acredito que essa issue seja só para disponibilizar os dados obtidos nas demais issues de analytics em um pandas dataframe
