### ISSUE TITLE
Analytics: matriz de correlação das medidas

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#235]
## Descrição da Issue
Deve-se criar uma matriz de correlação de todas as métricas coletadas até o momento, de maneira que se possa verificar se existem dados que se correlacionem, possuem semelhanças, possam ser analisados em conjunto e afins.

### Tasks:
- [ ] Criar matriz com todas as medidas
- [ ] Criar correlação de todas as métricas com todas as métricas
- [ ] Expor os resultados

### Critérios de aceitação
- [ ] Matriz de correlação criada
- [ ] A relação das métricas deve ser de fácil visualização para o usuário da tabela

**Comment by Phe0** [comment]
Sugiro dar uma lida no matérial q o professor hilmer enviou no discord, ele mandou um slide mostrando mais ou menos como plotar essa matriz utilizando pandas
