### ISSUE TITLE
Anaytics: Dataframe de métricas

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#240]
## Descrição da Issue
Deve-se construir um dataframe consolidade, com medidas e indicadores calculados de cada microsserviço, possuindo a estrutura: m1 m2 m3 m7 m8 m9 asc1 ac1 asc2 ac2 totalAC1 totalAC2 repository version ncloc coverage

### Tasks:
- [ ] Construir o dataframe
- [ ] Inserir as métricas
- [ ] Analisar os microsserviços

### Critérios de aceitação
- [ ] Dataframes de todos os microsserviços criados

**Comment by Phe0** [comment]
É necessário que todas as métricas estejam coletadas corretamente pra concluir essa tarefa, mas sugiro ir se ambientando com o jupyter notebook e ir tentando gerar uns dataframes lá
