### ISSUE TITLE
Correção da página de protótipo de alta fidelidade

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#243]
## Descrição da Issue
De acordo com o feedback do professor, o documento de protótipo de alta fidelidade não demonstra sua evolução incremental. Deve-se arrumar a página da wiki relacionada.

### Tasks:
- [ ] Demonstrar a evolução incremental do protótipo
- [ ] Adicionar prints e explicações

### Critérios de aceitação
- [ ] Página arrumada de acordo com o feedback
