### ISSUE TITLE
Análises dos testes de aceitação

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#246]
## Descrição da Issue
Deve-se fazer uma análise dos testes de aceitação do projeto, para se poder ver se os goals definidos no GQM e a visão do produto foram alacançadas

### Tasks:
- [ ] Analisar os valores dos testes de aceitaçao
- [ ] Transformar as análises em texto explicativo

### Critérios de aceitação
- [ ] Texto e tabela de explicação na wiki
