### ISSUE TITLE
Documento de Arquitetura

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#49]
## Nome da Issue
Elaborar documento de visão

## Descrição da Issue
Elaborar o documento de arquitetura do projeto que descreve questões mais técnicas e de tecnologias, metologias de desenvolvimento do projeto. Deve conter as seções descritas abaixo.

### Tasks:
- [ ] Finalidade
- [ ] Escopo
- [ ] Representação da Arquitetura, arquitetural e diagramas
- [ ] Metas e restrições da arquitetura
- [ ] Visão de implementação e diagramas

### Critérios de aceitação
- [ ] Com todos os tópicos bem escritos
- [ ] De acordo com as decisões de projeto
- [ ] Com referências
