### ISSUE TITLE
Backlog do Produto

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#50]
## Nome da Issue
Elaborar e priorizar o backlog do produto

## Descrição da Issue
Elaborar e priorizar o backlog do produto de acordo com as técnicas realizadas e os requistos levantados.

### Tasks:
- [ ] Criar épicos
- [ ] Criar features
- [ ] Criar histórias de usuário

### Critérios de aceitação
- [ ] Priorizado
- [ ] De fácil visualização
- [ ] De acordo com a notação correta
