### ISSUE TITLE
Histórias de Usuário

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#51]
## Nome da Issue
Criação das histórias de usuário

## Descrição da Issue
Criar as primeiras histórias de usuário que serão dadas nas sprints de projeto até a Release 1, de acordo com o backlog e roadmap do produto.

### Tasks:
- [x] Criar histórias de usuário

### Critérios de aceitação
- [x] Com a notação correta
- [x] De fácil entendimento
- [x] Seguindo o backlog e roadmap do produto
