### ISSUE TITLE
Manual de Identidade Visual

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#52]
## Nome da Issue
Manual de Identidade Visual

## Descrição da Issue
Criar o manual de identidade visual do projeto, de acordo com o nome escolhido.

### Tasks:
- [x] Logo
- [x] Tipografia
- [x] Paleta de Cores

### Critérios de aceitação
- [x] Ter as tasks acimas completas
- [x] Deve estar de acordo com o protótipo

**Comment by Victor-Buendia** [comment]
[IDV Eccoar.pdf](https://github.com/fga-eps-mds/2020.2-Eccoar/files/6086334/IDV.Eccoar.pdf)
Resultado final da documentação em PDF. Pode ser encontrada no Figma [aqui](https://www.figma.com/file/y5ak8SDlqgaPKGfPIble7R/Projeto-Eccoar?node-id=19%3A2).

**Comment by Victor-Buendia** [comment]
@MatheusBlanco Quem faz a review aqui? Ou pode fechar a issue.

**Comment by Victor-Buendia** [comment]
Nova versão. Versão Final.
[Uploading IDV Eccoar.pdf…]()

**Comment by MatheusBlanco** [comment]
Perfeito, só colocar na wiki e abrir um PR
