### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#53]
## Nome da Issue
Protótipo de alta fidelidade

## Descrição da Issue
Fazer o design das primeiras telas do protótipo de alta fidelidade, para que possam ser usadas na primeira sprint de código. Não precisa estar animado 

### Tasks:
- [x] Criar telas das principais funcionalidades
- [x] Se utilizar do [backlog do produto](https://docs.google.com/spreadsheets/d/1BWgLcNVli3B1-w7T_7j1X5dLGAuc9UeXKd8Q0DTE0Eg/edit?usp=sharing), olhar a priorização de issues e fazer apenas as mais importantes
- [x] Se utilizar do sequenciador do [Lean Inception](https://app.mural.co/invitation/mural/fgaepsmds202027717/1613056199650?sender=ud8413517a97742009ec54625&key=a5e2bf67-d258-413c-9fe6-58f12d85594f) para fazer apenas as telas das funcionalidades principais do MVP

### Critérios de aceitação
- [x] De acordo com o Manual de IDV

**Comment by Phe0** [comment]
![photo5046438903690668371](https://user-images.githubusercontent.com/31973465/110038593-affcc000-7d1e-11eb-90a7-0d436194cc92.jpg)

**Comment by Phe0** [comment]
Link de uma das versões do protótipo: https://www.figma.com/proto/y5ak8SDlqgaPKGfPIble7R/Projeto-Eccoar?node-id=81%3A470&scaling=min-zoom

**Comment by Victor-Buendia** [comment]
[Protótipo.pdf](https://github.com/fga-eps-mds/2020.2-Eccoar/files/6095259/Prototipo.pdf)
Uma outra versão de esboço do protótipo.

**Comment by Victor-Buendia** [comment]
Link de outra versão do protótipo (a usada é a que o @Phe0 enviou acima): https://www.figma.com/proto/y5ak8SDlqgaPKGfPIble7R/Projeto-Eccoar?node-id=32%3A135&scaling=scale-down
