### ISSUE TITLE
Realizar testes do protótipo

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#54]
## Nome da Issue
Realizar testes do protótipo

## Descrição da Issue
Realizar testes do protótipo com possíveis usuários reais (membros da família), documentar os resultados

### Tasks:
- [x] Realizar teste com pelo menos uma pessoa (por membro na issue)
- [x] Documentar o processo (pode ser vídeo)
- [x] Criar roteiro de seguimento
- [x] Anotar as mudanças requisitadas

### Critérios de aceitação
- [x] 3 testes realizados
- [x] Documentados

**Comment by MatheusBlanco** [comment]
Roteiro: https://fga-desenho-2019-2.github.io/Wiki/iniciativas_extras/testes_de_usabilidade/v1/roteiro/

Análise: https://fga-desenho-2019-2.github.io/Wiki/iniciativas_extras/testes_de_usabilidade/v1/analise/
