### ISSUE TITLE
Roadmap do produto

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#55]
## Nome da Issue
Roadmap do produto

## Descrição da Issue
Elaborar o roadmap do produto pelo menos até a R1, de acordo com o backlog do produto

### Tasks:
- [x] Priorizar issues de acordo com necessidade
- [x] Montar um roadmap que inclui funcionalidades core pra R1

### Critérios de aceitação
- [x] De acordo com o backlog
- [x] Bem priorizado

**Comment by MatheusBlanco** [comment]
O roadmap está sendo construído no [Miro](https://miro.com/welcomeonboard/rkyj4zgjqZB9xuzFd4K6cnqKTDTO2T1balJCMzKxIY7hwkMKujWNZhvnZwBKRYJ5), por ser uma plataforma que permite a mais fácil visualização.
