### ISSUE TITLE
Finalizar o Lean Inception

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#58]
## Descrição da Issue
Terminar o Lean Inception de acordo com os feedbacks do professor.

### Tasks:
- [x] Arrumar personas
- [x] Fechar o Canvas MVP

### Critérios de aceitação
- [x] Lean Inception documentado na Wiki
- [x] Deve ter a visão de usuário sobre o Lean também
- [x] Incluir o professor como stakeholder e persona
