### ISSUE TITLE
Configurar ambientes de desenvolvimento do back-end

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#66]
## Descrição da Issue
Configurar ambientes de desenvolvimento de todos os serviços escolhidos para microsserviços.

### Tasks:
- [ ] Ambiente de usuário (mariaDB configurado)
- [ ] Ambiente de denúncia (mariaDB configurado)
- [ ] Ambiente de e-mail (REDIS)
- [ ] Ambiente de relatórios

### Critérios de aceitação
- [ ] De acordo com a tecnologia escolhida
- [ ] Seguir princípios do clean arquiteture
- [ ] Estar dockerizado
