### ISSUE TITLE
Criar Tabela de Análise de EVM

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#67]
## Descrição da Issue
Criar a tabela de análise e compilação de dados para a documentação da EVM, para que se possar criar uma análise de custos significativa, por sprint de código, do produto.

### Tasks:
- [x] Criar boylerplate para receber dados da sprint
- [x] Criar cálculos para se estimar o preço das issues
- [x] Gráficos resumo

### Critérios de aceitação
- [x] Poder ser utilizado semanalmente para se estimar o custo do projeto
- [x] Gráficos resumo que mostrem o valor planejado e o valor agregado para a sprint
- [x] Variação do Custo e Prazo
