### ISSUE TITLE
Estilização da Wiki

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#68]
## Descrição da Issue
Deve se estilizar a wiki de documentação de acordo com a nossa nova identidade visual.

### Tasks:
- [x] Mudar as cores principais
- [x] Aplicar a logo na página inicial, na navbar e na tab do Chrome (favicon)
- [x] Arrumar os links quebrados em produção
- [x] Arrumar os links que levam para os repositórios (apontar pra organização), no cabeçalho e na página principal

### Critérios de aceitação
- [x] Cores de acordo com a IDV
- [x] Logo de acordo com a IDV
- [x] Links arrumados
