### ISSUE TITLE
Estudo de testes do front

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#70]
## Descrição da Issue
Como a matéria possui como requisito 90% de cobertura de testes, é essencial que façamos testes no front-end também. Por ser uma área mais nebulosa, Pedro Féo se voluntariou a estudar para entender melhor.

### Tasks:
- [ ] Estudar testes em ReactJS com TypeScript
- [ ] Criar um documento manual para a realização dos mesmos

### Critérios de aceitação
- [ ] Estudar a react-testing-library
- [ ] Documento de fácil entendimento para aplicação dos testes
