### ISSUE TITLE
Criação de componente estático - NavBar

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#71]
## Descrição da Issue
Deve-se criar uma navbar estática como componente reutilizável, para que se possa ser utilizada no front-end de maneira simples e direta.

### Tasks:
- [x] Criar o componente de navbar
- [x] Tornar fácilmente reutilizável

### Critérios de aceitação
- [x] Em typescript, reactJS
- [x] De acordo com o protótipo
