### ISSUE TITLE
Criação do BackGround do Front-end

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#72]
## Descrição da Issue
Deve-se estilizar a tela de fundo da aplicação, para que possa aparecer em todas as futuras telas da aplicação.

### Tasks:
- [ ] Criar o background
- [ ] Tornar visível em todas as telas

### Critérios de aceitação
- [ ] Em typescript, reactJS
- [ ] De acordo com o protótipo
