### ISSUE TITLE
Criação de componente - Botão

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#73]
## Descrição da Issue
Deve-se criar um botão como componente reutilizável, para que se possa ser utilizada no front-end de maneira simples e direta.

### Tasks:
- [x] Criar o componente de botão
- [x] Tornar fácilmente reutilizável

### Critérios de aceitação
- [ ] Em typescript, reactJS
- [ ] De acordo com o protótipo
