### ISSUE TITLE
Criação de componente - Input

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#75]
## Descrição da Issue
Deve-se criar um input como componente reutilizável, para que se possa ser utilizada no front-end de maneira simples e direta.

### Tasks:
- [x] Criar o componente de input
- [x] Tornar fácilmente reutilizável

### Critérios de aceitação
- [ ] Em typescript, reactJS
- [ ] De acordo com o protótipo
- [ ] Deve conter Label
