### ISSUE TITLE
Criação de componente - Card e upvote de denúncia

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#76]
## Descrição da Issue
Deve-se criar um card de denúncia, que contem botão de upvote, como componente reutilizável, para que se possa ser utilizada no front-end de maneira simples e direta.

### Tasks:
- [x] Criar o componente de card com botão de upvote
- [x] Tornar fácilmente reutilizável

### Critérios de aceitação
- [ ] Em typescript, reactJS
- [ ] De acordo com o protótipo
