### ISSUE TITLE
Documentação Planning Sprint 4

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#77]
## Descrição da Issue
Adicionar à wiki a documentação de planning da sprint em questão contendo as duplas de pareamento definidas, as issues/histórias de usuário escolhidas para serem trabalhadas, contendo pontuação e encarregados da mesma. 

### Tasks:
- [ ] Duplas de pareamento
- [ ] Issues/histórias de usuário

### Critérios de aceitação
- [ ] Documentação na wiki
- [ ] Justificativa para escolha dos pareamentos
- [ ] Tabela de issues com responsáveis e pontuação estimada
