### ISSUE TITLE
Estudo de Implantação

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#79]
## Descrição da Issue
Estudar conceitos para se realizar a implantação do sistema em produção.

### Tasks:
- [ ] Estudar ferramentas de deploy
- [ ] Estudar provedores
- [ ] Estudar realização de CI/CD
- [ ] Estudar melhores ferramentas para tal.

### Critérios de aceitação
- [ ] Bom entendimento de como realizar o deploy
