### ISSUE TITLE
Configurar CI/CD

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#97]
## Descrição da Issue
Configurar as pipelines de integração e deploy contínuos para os serviços do Eccoar.

### Tasks:
- [ ] Configurar pipelines de integração contínua
- [ ] Configurar pipelines de deploy contínuo
- [ ] Configurar testes de integração

### Critérios de aceitação
- [ ] CI capaz de realizar integração contínua, checando os testes
- [ ] CD capaz de realizar o deploy contínuo para o ambiente em produção.
