### ISSUE TITLE
Preparar documentações para a R1

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#99]
## Descrição da Issue
Conferir e preparar as documentações existentes para serem apresentadas na Release 1 da disciplina Engenharia de Produto de Software.

### Tasks:
- [ ] Conferir documentações existentes
- [ ] Criar documentações faltantes

### Critérios de aceitação
- [ ] Todas as documentações estarem prontas para serem apresentadas na R1
